//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK3BB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GK3BB.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2010 Brad Farris.
        /// </summary>
        internal static string AboutCopyright1 {
            get {
                return ResourceManager.GetString("AboutCopyright1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under the GNU GPL.
        /// </summary>
        internal static string AboutCopyright2 {
            get {
                return ResourceManager.GetString("AboutCopyright2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string AboutCredits {
            get {
                return ResourceManager.GetString("AboutCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://gk3tools.sourceforge.net.
        /// </summary>
        internal static string AboutLink {
            get {
                return ResourceManager.GetString("AboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabriel Knight 3 Barn Browser.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CompressionNone {
            get {
                return ResourceManager.GetString("CompressionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this is a compiled Sheep script. To preview it the Browser needs a copy of the Sheep library, but it couldn&apos;t find it. Please make sure the Sheep library is in the same folder as the Browser executable and try again..
        /// </summary>
        internal static string CouldntFindSheepError {
            get {
                return ResourceManager.GetString("CouldntFindSheepError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barn.
        /// </summary>
        internal static string ListBarn {
            get {
                return ResourceManager.GetString("ListBarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        internal static string ListCompression {
            get {
                return ResourceManager.GetString("ListCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string ListFilename {
            get {
                return ResourceManager.GetString("ListFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ListSize {
            get {
                return ResourceManager.GetString("ListSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ListType {
            get {
                return ResourceManager.GetString("ListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert bitmaps.
        /// </summary>
        internal static string MainMenuConvertBitmaps {
            get {
                return ResourceManager.GetString("MainMenuConvertBitmaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress files.
        /// </summary>
        internal static string MainMenuDecompress {
            get {
                return ResourceManager.GetString("MainMenuDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainMenuExit {
            get {
                return ResourceManager.GetString("MainMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all bitmaps.
        /// </summary>
        internal static string MainMenuExtractAllBitmaps {
            get {
                return ResourceManager.GetString("MainMenuExtractAllBitmaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all docs.
        /// </summary>
        internal static string MainMenuExtractAllDocs {
            get {
                return ResourceManager.GetString("MainMenuExtractAllDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all HTML files.
        /// </summary>
        internal static string MainMenuExtractAllHtml {
            get {
                return ResourceManager.GetString("MainMenuExtractAllHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all wavs.
        /// </summary>
        internal static string MainMenuExtractAllWavs {
            get {
                return ResourceManager.GetString("MainMenuExtractAllWavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract selected files.
        /// </summary>
        internal static string MainMenuExtractSelected {
            get {
                return ResourceManager.GetString("MainMenuExtractSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MainMenuFile {
            get {
                return ResourceManager.GetString("MainMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MainMenuHelp {
            get {
                return ResourceManager.GetString("MainMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open barn....
        /// </summary>
        internal static string MainMenuOpenBarn {
            get {
                return ResourceManager.GetString("MainMenuOpenBarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview file.
        /// </summary>
        internal static string MainMenuPreviewFile {
            get {
                return ResourceManager.GetString("MainMenuPreviewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set extract to path....
        /// </summary>
        internal static string MainMenuSetExtractionPath {
            get {
                return ResourceManager.GetString("MainMenuSetExtractionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string MainMenuTools {
            get {
                return ResourceManager.GetString("MainMenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT animation.
        /// </summary>
        internal static string TypeAct {
            get {
                return ResourceManager.GetString("TypeAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation script.
        /// </summary>
        internal static string TypeAnm {
            get {
                return ResourceManager.GetString("TypeAnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap.
        /// </summary>
        internal static string TypeBmp {
            get {
                return ResourceManager.GetString("TypeBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room geometry.
        /// </summary>
        internal static string TypeBsp {
            get {
                return ResourceManager.GetString("TypeBsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor.
        /// </summary>
        internal static string TypeCur {
            get {
                return ResourceManager.GetString("TypeCur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word document.
        /// </summary>
        internal static string TypeDoc {
            get {
                return ResourceManager.GetString("TypeDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        internal static string TypeExe {
            get {
                return ResourceManager.GetString("TypeExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string TypeFon {
            get {
                return ResourceManager.GetString("TypeFon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEngine script.
        /// </summary>
        internal static string TypeGas {
            get {
                return ResourceManager.GetString("TypeGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML document.
        /// </summary>
        internal static string TypeHtml {
            get {
                return ResourceManager.GetString("TypeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model geometry.
        /// </summary>
        internal static string TypeMod {
            get {
                return ResourceManager.GetString("TypeMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOM animation script.
        /// </summary>
        internal static string TypeMom {
            get {
                return ResourceManager.GetString("TypeMom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room lightmap.
        /// </summary>
        internal static string TypeMul {
            get {
                return ResourceManager.GetString("TypeMul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noun-verb-case file.
        /// </summary>
        internal static string TypeNvc {
            get {
                return ResourceManager.GetString("TypeNvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene definition.
        /// </summary>
        internal static string TypeScn {
            get {
                return ResourceManager.GetString("TypeScn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEQ file?.
        /// </summary>
        internal static string TypeSeq {
            get {
                return ResourceManager.GetString("TypeSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheep script.
        /// </summary>
        internal static string TypeShp {
            get {
                return ResourceManager.GetString("TypeShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene initialization.
        /// </summary>
        internal static string TypeSif {
            get {
                return ResourceManager.GetString("TypeSif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound track file.
        /// </summary>
        internal static string TypeStk {
            get {
                return ResourceManager.GetString("TypeStk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text document.
        /// </summary>
        internal static string TypeTxt {
            get {
                return ResourceManager.GetString("TypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAV audio.
        /// </summary>
        internal static string TypeWav {
            get {
                return ResourceManager.GetString("TypeWav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAK dialog file.
        /// </summary>
        internal static string TypeYak {
            get {
                return ResourceManager.GetString("TypeYak", resourceCulture);
            }
        }
    }
}
