COMPILER = gmcs
COMPILER_FLAGS = -d:D3D_DISABLED -r:Tao.OpenGl -r:Tao.Sdl -r:main.dll
EXECUTABLE = viewer.exe

SOURCES = MonoMain.cs OpenGLRenderWindow.cs Input.cs VerbPickerManager.cs

$(EXECUTABLE):
	cp ../Main/main.dll .
	$(COMPILER) $(COMPILER_FLAGS) $(SOURCES) -out:$(EXECUTABLE)
	
clean:
	rm $(EXECUTABLE)