#ifndef SHEEPERRORCODES_H
#define SHEEPERRORCODES_H

#define SHEEP_SUCCESS 0
#define SHEEP_ERROR -1
#define SHEEP_ERR_NO_SUCH_FUNCTION -2
#define SHEEP_ERR_FILE_NOT_FOUND -10
#define SHEEP_ERR_INVALID_FILE_FORMAT -11
#define SHEEP_GENERIC_COMPILER_ERROR -100
#define SHEEP_ERR_NO_CONTEXT_AVAILABLE -101
#define SHEEP_ERR_EMPTY_STACK -102
#define SHEEP_ERR_WRONG_TYPE_ON_STACK -103
#define SHEEP_ERR_CANT_RESUME -104
#define SHEEP_ERR_INVALID_ARGUMENT -105
#define SHEEP_ERR_VARIABLE_NOT_FOUND -106
#define SHEEP_ERR_VARIABLE_INCORRECT_TYPE -107
#define SHEEP_GENERIC_VM_ERROR -200
#define SHEEP_UNKNOWN_ERROR_PROBABLY_BUG -1000
#define SHEEP_SUSPENDED 2

#endif // SHEEPERRORCODES_H
